apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-k8-backend-dep
  labels:
    app: todo-k8-backend-dep
spec:
  selector:
    matchLabels:
      app: todo-k8-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-k8-backend
    spec:
      containers:
        - name: todo-k8-backend
          image: rahuldesar/todo-k8-backend:0.0.1
          imagePullPolicy: IfNotPresent
---
